### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by wbolster** [bmallred/evil-colemak-minimal#1]
hi, evil-colemak-basics author here. i'm interested in the reasons for your "fork". care to elaborate?

**Comment by bmallred** [comment]
My keybindings differ from most of the Colemak Vim bindings I have seen (mainly to avoid heavy remapping of normal Qwerty bindings).

I liked how your package was easy to follow and so used it as a template. Was this okay?

**Comment by wbolster** [comment]
of course that's okay!

i got confused by the word "minimal" in the name though. my "basic" mappings are actually pretty minimal, and yours actually redesign the keyboard.

perhaps you can make this more clear in your readme?

fyi, i have just improved my readme at https://github.com/wbolster/evil-colemak-basics a bit. perhaps you have feedback to share.

**Comment by bmallred** [comment]
Sure thing (on both clearing up mine and reading through yours)! I'll probably be on late tonight or early tomorrow so can take a peek then.

Yeah sorry about the name. Typical "developer can't name shit" syndrome :-)

**Comment by bmallred** [comment]
Closing with the latest update to the README. efa309239cc0a0b74c3e9734d871d6ecb03cf60f

**Comment by bmallred** [comment]
@wbolster the changes to your README look good.

I must say when I switched I gave something similar to your changes a good trial for about a month. Unfortunately when I learned Vim, and even to this day I still do it just in my head, the mnemonics were a huge part of how I interact with the system. Something like "(d)elete (i)n (w)ord" was hard to replace. I wish it would've been that easy because honestly your package does make the most logical sense.

**Comment by wbolster** [comment]
i will definitely steal your nice tables, and hack in window movement bindings in my package as well.

**Comment by wbolster** [comment]
i am actually quite happy with the setup from `evil-colemak-basics`, which works perfectly for most of my editing workflow. what i do miss though is an easy to reach 'end of word' (easy to reach `e` on qwerty, `j` on colemak with my package), but i am undecided on how to resolve it. ideas welcome since we are both trying to address the same "vim+colemak" problem.

**Comment by bmallred** [comment]
Yeah I'm using `l` at the moment which isn't bad and I just trained my brain to say "last". I'll open up an "issue" on your end to brainstorm stuff. Probably will be on tomorrow and toy with ideas over some coffee :-)

**Comment by wbolster** [comment]
cross referencing https://github.com/wbolster/evil-colemak-basics/issues/2
