### ISSUE TITLE
Movement keys should not be overriden in emacs state 

### ISSUE THREAD

**Issue by moesasji** [bmallred/evil-colemak-minimal#3]
I really like the rather minimal changes resulting from splitting the movement keys over the two hands. However your current implementation breaks packages that rely on using emacs state to function properly, such as mu4e and magit.

To avoid problems for packages that rely on unchanged keybindings you should only override evil keys in 'real' evil modes; but leave the keybindings in emacs state as the native keys as that is what emacs state should be.

Just removing all occurrences of 'emacs' in your code seems to be all that is needed to fix the problems I had with mu4e and magit after enabling evil-colemak-minimal.

Note that If you want to have the ability to easily add "nest"-movement in emacs-state you could include a function to add those movement similar to the evil-add-hjkl-bindings  function for native Evil. This however should not be activated by default.

btw) The "convenience" bindings for folding in my opinion don't belong in this package as they rely on hs-mode, so not functional if one uses other folding packages like vimish-fold.

**Comment by bmallred** [comment]
@moesasji thanks for the feedback! I am hoping to have some time this weekend or next week to look at implementing some of these changes but PRs are always welcome!

Also @wbolster has a nice setup for colemak bindings you may want to check out at https://github.com/wbolster/evil-colemak-basics

**Comment by wbolster** [comment]
obviously i love my key bindings and i think that they are the best thing in the world... but i must say that it sometimes needs some tweaks to make it not mess up `magit` (for instance). see my dotfiles for details: https://github.com/wbolster/dotfiles/tree/master/Emacs

**Comment by bmallred** [comment]
@moesasji i haven't forgot about this and going to take a look at it today!
